version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/src/app
    ports:
      - "3000:3000"
    # command: sh -c 'npm run dev'
    environment:
      # ここにバックエンドのホスト名などを追加
      BACKEND_HOST: 'laravel.test'
      BACKEND_PORT: '${APP_PORT:-80}'
    networks:
      - sail

networks:
  sail:
    external: true
    name: sail
